default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: 'truckers_development'
  # username: 'postgres'
  # password: 'postgres'
  host: localhost
  port: 5432
